# Generated by Django 5.0 on 2024-02-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReview',
        ),
    ]
